In [ ]:
%pip install py-synthpop

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting py-synthpop
  Downloading py_synthpop-0.1.2-py3-none-any.whl (19 kB)
Installing collected packages: py-synthpop
Successfully installed py-synthpop-0.1.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from synthpop import Synthpop

In [ ]:
df = pd.read_csv("/content/drive/Shareddrives/SI670 Final_Proj/transactions.csv")

In [ ]:
df.head()

,OBJECTID,AGENCY,TRANSACTION_DATE,TRANSACTION_AMOUNT,VENDOR_NAME,VENDOR_STATE_PROVINCE,MCC_DESCRIPTION
0,481,Department of Youth Rehabilitation Services,2009-01-06T00:00:00.000Z,977.00,MY SAFE FOOD HANDLER,MD,Business Services Not Elsewhere Classified
1,482,Department of Youth Rehabilitation Services,2009-01-06T00:00:00.000Z,-25.61,AMES SAFETY ENVELOPE C,MA,Miscellaneous Publishing And Printing
2,483,DC Public Library,2009-01-07T00:00:00.000Z,1035.29,WWW.AIA.ORG,DC,"Membership Organizations, Not Elsewhere Classi..."
3,484,Office of the State Superintendent of Education,2009-01-06T00:00:00.000Z,222.40,DELTA 00675274330522,TN,Delta
4,485,Office of the State Superintendent of Education,2009-01-06T00:00:00.000Z,222.40,DELTA 00675274330500,TN,Delta

In [ ]:
df['Date'] = df['TRANSACTION_DATE'].apply(lambda x: x.split('T')[0])

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275127 entries, 0 to 275126
Data columns (total 8 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   OBJECTID               275127 non-null  int64
 1   AGENCY                 275127 non-null  object
 2   TRANSACTION_DATE       275127 non-null  object
 3   TRANSACTION_AMOUNT     275127 non-null  float64
 4   VENDOR_NAME            275088 non-null  object
 5   VENDOR_STATE_PROVINCE  274898 non-null  object
 6   MCC_DESCRIPTION        275109 non-null  object
 7   Date                   275127 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 16.8+ MB

In [ ]:
df_2009 = df[df['Date'].dt.year==2009].drop(['OBJECTID',
                                            'TRANSACTION_DATE',
                                            'VENDOR_NAME',
                                            'VENDOR_STATE_PROVINCE',
                                            'MCC_DESCRIPTION'], axis=1)
df_2009.head()

,AGENCY,TRANSACTION_AMOUNT,Date
0,Department of Youth Rehabilitation Services,977.00,2009-01-06
1,Department of Youth Rehabilitation Services,-25.61,2009-01-06
2,DC Public Library,1035.29,2009-01-07
3,Office of the State Superintendent of Education,222.40,2009-01-06
4,Office of the State Superintendent of Education,222.40,2009-01-06

In [ ]:
df_2009['Date'] = pd.to_numeric(df_2009['Date'])

In [ ]:
df_2009.head()

,AGENCY,TRANSACTION_AMOUNT,Date
0,Department of Youth Rehabilitation Services,977.00,1231200000000000000
1,Department of Youth Rehabilitation Services,-25.61,1231200000000000000
2,DC Public Library,1035.29,1231286400000000000
3,Office of the State Superintendent of Education,222.40,1231200000000000000
4,Office of the State Superintendent of Education,222.40,1231200000000000000

In [ ]:
df_2009.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28235 entries, 0 to 42999
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AGENCY              28235 non-null  object
 1   TRANSACTION_AMOUNT  28235 non-null  float64
 2   Date                28235 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 882.3+ KB

In [ ]:
spop = Synthpop(visit_sequence=[2, 1, 0])

In [ ]:
data_types = {"AGENCY": "category",
              "TRANSACTION_AMOUNT": "float",
              "Date": "int"}

spop.fit(df_2009, data_types)

train_Date
train_TRANSACTION_AMOUNT
train_AGENCY

In [ ]:
spop_syn = spop.generate(len(df_2009))

generate_Date
generate_TRANSACTION_AMOUNT
generate_AGENCY

In [ ]:
spop_syn.head()

,AGENCY,TRANSACTION_AMOUNT,Date
0,Department of Youth Rehabilitation Services,848.00,1244073600000000000
1,Department of Health,1892.00,1242950400000000000
2,Office of Finance & Resource Management,1801.31,1240444800000000000
3,Metropolitan Police Department,135.98,1246060800000000000
4,Fire & Emergency Medical Services,521.12,1257292800000000000

In [ ]:
spop_syn['Date'] = pd.to_datetime(spop_syn['Date'])

In [ ]:
spop_syn.head()

                                         AGENCY  TRANSACTION_AMOUNT       Date
0  Department of  Youth Rehabilitation Services              848.00 2009-06-04
1                          Department of Health             1892.00 2009-05-22
2       Office of Finance & Resource Management             1801.31 2009-04-23
3                Metropolitan Police Department              135.98 2009-06-27
4             Fire & Emergency Medical Services              521.12 2009-11-04

In [ ]:
spop_syn.to_csv('spop_syn.csv', index=False)

In [ ]:
spop.method

AGENCY                  cart
TRANSACTION_AMOUNT      cart
Date                  sample
dtype: object

In [ ]:
spop.visit_sequence

AGENCY                2
TRANSACTION_AMOUNT    1
Date                  0
dtype: int64

In [ ]:
spop.predictor_matrix

                    AGENCY  TRANSACTION_AMOUNT  Date
AGENCY                   0                   1     1
TRANSACTION_AMOUNT       0                   0     1
Date                     0                   0     0